version: '3.1'

services:

  archisaurus:
    image: peea
    restart: always
    ports: 
      - 18080:8080
    
  course-management-mysql:
    image: mysql
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: course_management
      MYSQL_ROOT_PASSWORD: root